#!/bin/bash

# This serves as the main entry point to the pseudo-shell.
# Right off the bat, we grab the current working directory and write it to a config file called
#	.root_dir that way every script can call it to figure out where it is in the *actual* file
#	system, allowing us to not only know where *we* are, but where all the other files are, as well.

root_dir=$(pwd)
export $root_dir
# shellcheck source=src/system_files/bin/sys_bin/error_report.sh
source $root_dir/system_files/bin/sys_bin/error_report.sh

echo -n "Initializing shell..."
echo -n "/" > $root_dir/system_files/bin/sys_bin/.current_dir
if does_admin_account_exist=$(cat $root_dir/system_files/config/users | grep "admin"); then
	echo "[ok]"
	if [[ $does_admin_account_exist == *"admin"* ]]; then
		echo "WARNING! Admin account has not been setup yet! Creating Admin account now..."
		if . ./system_files/bin/sys_bin/setup_admin; then
			echo "Proceeding to login screen..."
			. ./system_files/bin/sys_bin/login
			exit 0
		else error "${0}: ${LINENO}: " "Failed to execute!"
		fi
	else
		echo "Proceeding to login screen..."
		. ./system_files/bin/sys_bin/login
		exit 0
	fi
else
	# shellcheck source=./system_files/bin/sys_bin/login
	. ./system_files/bin/sys_bin/login
	exit 0
fi
